image: "ruby:2.1"

services:
  - mysql:latest
  - redis:latest

cache:
  key: "ruby21"
  paths:
  - vendor

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "1"

before_script:
  - source ./scripts/prepare_build.sh
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - cp config/gitlab.yml.example config/gitlab.yml
  - touch log/application.log
  - touch log/test.log
  - bundle install --without postgres production --jobs $(nproc)  "${FLAGS[@]}"
  - RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load db:migrate

spec:feature:
  script:
    - RAILS_ENV=test SIMPLECOV=true bundle exec rake spec:feature
  tags:
    - ruby
    - mysql

spec:api:
  script:
    - RAILS_ENV=test SIMPLECOV=true bundle exec rake spec:api
  tags:
    - ruby
    - mysql

spec:benchmark:
  script:
    - RAILS_ENV=test bundle exec rake spec:benchmark
  tags:
    - ruby
    - mysql
  allow_failure: true

spec:other:
  script:
    - RAILS_ENV=test SIMPLECOV=true bundle exec rake spec:other
  tags:
    - ruby
    - mysql

spinach:project:
  script:
    - RAILS_ENV=test SIMPLECOV=true bundle exec rake spinach:project
  tags:
    - ruby
    - mysql

spinach:other:
  script:
    - RAILS_ENV=test SIMPLECOV=true bundle exec rake spinach:other
  tags:
    - ruby
    - mysql

teaspoon:
  script:
    - RAILS_ENV=test bundle exec teaspoon
  tags:
    - ruby
    - mysql

rubocop:
  script:
    - bundle exec rubocop
  tags:
    - ruby
    - mysql

brakeman:
  script:
    - bundle exec rake brakeman
  tags:
    - ruby
    - mysql

flog:
  script:
    - bundle exec rake flog
  tags:
    - ruby
    - mysql

flay:
  script:
    - bundle exec rake flay
  tags:
    - ruby
    - mysql
  allow_failure: true
